WowRarity/Rarity

- Options_Defaults.lua
Current rarity is 1 in 20 but according to my personal experience and the droprate its much more rare.
1.6%: https://www.wowhead.com/item=170072/armored-vaultbot
> DB: Fix rarity of Armored Vaultbot

- Options_Defaults.lua
**Hopecrusher Gargon** drops for **Venthyr** and not **Necrolord**. I also noticed that the constant was spelt incorrectly for **Harika the Horrid**.
My editor also stripped some white space. Sorry if that is an issue.
> Fix incorrect covenant for Hopecrusher Gargon

- Locales.lua
- Options_Defaults.lua
This is a little different to most mounts that drop from NPC's.
The [Impressionable Gorger Spawn](https://www.wowhead.com/item=180583/impressionable-gorger-spawn#comments) has a chance to drop from the [Worldedge Gorger](https://www.wowhead.com/npc=160821/worldedge-gorger). 
This item starts a quest chain where you have to complete a daily quest 7(?) times. After that you will learn the [Loyal Gorger](https://www.wowhead.com/spell=333027/loyal-gorger).
I used the [Torn Invitation](https://github.com/SacredDuckwhale/Rarity/blob/1809d53b8abbf4bf492a43602d2c662b155c23e6/Options_Defaults.lua#L715) as a template, since that is also an item which doesn't directly give you the mount.
> Add Impressionable Gorger Spawn (Loyal Gorger)

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added a missing 9.0 mount to the database. This is a rare event which ends with a cache that may contain this mount
https://www.wowhead.com/item=183741/ascended-skymane
> DB: Added missing mount: Ascended Skymane

- Options_Defaults.lua
Added missing defeat detection for the pet: Oily Invertebrate
> DB: Added missing defeat detection for Oily Invertebrate

- Locales.lua
- Options_Defaults.lua
DB: Added missing 8.0 pet: Filthy Bucket ([https://www.wowhead.com/item=160704/filthy-bucket](https://www.wowhead.com/item=160704/filthy-bucket))
> DB: Added missing 8.0 pet: Filthy Bucket

- Options_Defaults.lua
Added defeat detection and a tooltipNPC for Sabriel the Bonecleaver's two mount drops. One of these are still not confirmed dropping on live, as this is one of the first days he is up - but as the mount is already in the DB, I updated the detection for both
> DB: Added defeat detection and tooltipNPC for Sabriel the Bonecleaver

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added another missing pet from 9.0. This time it's the [Skittering Venomspitter](https://www.wowhead.com/item=181173/skittering-venomspitter) which is contained in a 'chest' in Maldraxxus
> DB: Added Skittering Venomspitter (pet)

- Core/EventHandlers.lua
- Locales.lua
- Options_Defaults.lua
Added the 9.0 pet [Bubbling Pustule](https://www.wowhead.com/item=181262/bubbling-pustule)
This is a drop contained in Slime-Coated Crate, a chest that got implemented a couple commits ago related to a toy. Code is modified to count both items
> DB: Added Bubbling Pustule (pet)

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added the 9.0 pet [Trapped Stonefiend](https://www.wowhead.com/item=180592/trapped-stonefiend). This can drop from [Bleakwood Chest](https://www.wowhead.com/object=353232/bleakwood-chest) in Revendreth.
> DB: Added Trapped Stonefiend (pet)

- .gitignore
- Core/GUI.lua
- Locales.lua
- Modules/Options/Options.lua
- Options_Defaults.lua
I've added a config menu to toggle Mounts, Battle Pets, and Toys & Items to be displayed by the tooltip.
The rationale was huge performance drops when opening the tooltip when I only really want to display mounts at the moment. Filtering out the unneeded collections makes it significantly quicker for me.
Also, sorry about the crud added to the .gitignore, it's from Visual Studio :)
> Added mount/item/pet filter

- Locales.lua
- Options_Defaults.lua
This [pet ](https://www.wowhead.com/item=183115/tower-deathroach)is dropping from multiple bosses within Torghast and not just the one that was listed. I only noticed because I had it drop from another boss. Also updated the drop chance to a better approximation
> DB: Updated Tower Deathroach's source and chance

- Locales.lua
- Options_Defaults.lua
I've added the pets aquired from Alchemy both in Legion and Battle for Azeroth. Both expansions added transmutations to create pets, and a few of those are rare drops with no other source.
Container 1: [Grumbling Sac](https://www.wowhead.com/item=160324/grumbling-sac) from Battle for Azeroth Alchemy: [Transmute: Meat to Pet](https://www.wowhead.com/spell=251808/transmute-meat-to-pet) may contain:
- [Wind-Up Frog](https://www.wowhead.com/item=163860/wind-up-frog)
- [Undulating Blue Sac](https://www.wowhead.com/item=163861/undulating-blue-sac)
- [Ball of Tentacles](https://www.wowhead.com/item=163858/ball-of-tentacles)
- [Baby Crawg](https://www.wowhead.com/item=163859/baby-crawg)
Container 2: [Growling Sac](https://www.wowhead.com/item=137608/growling-sac) from Legion Alchemy: [Transmute: …
> Added the pets from Alchemy

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added the 9.0 toy [Battlecry of Krexus](https://www.wowhead.com/item=184318/battlecry-of-krexus). This toy can be looted from a [chest](https://www.wowhead.com/object=352086/blackhound-cache) in Maldraxxus. This is practically a Necrolord only toy, but I have not implemented the covenant restrictions on the item, given that Blizzard has mechanics preventing other covenants to reach this chest in the first place. There are reports of other covenants gaining access to this chest and thus having looted the toy, but this seems to have been hotfixed.
> DB: Added Battlecry of Krexus

- Locales.lua
- Options_Defaults.lua
Added another pet from 9.0 - this time the [Larion Pouncer](https://www.wowhead.com/item=184401/larion-pouncer) from a rare in Bastion which spawns from Anima Conductor rank 3. There is not enough data to tell if this is a Kryian covenant only drop, so I haven't flagged it as a requirement. Will just have to keep an eye on it.
> DB: Added Larion Pouncer (pet)

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added the pet [Soullocked Sinstone](https://www.wowhead.com/item=180589/soullocked-sinstone#contained-in-object) from a chest in Revendreth. Chest has multiple spawn locations, hence the lack of coordinates. Not much recorded data on it yet, but I have confirmed the pet on the AH, so it is obtainable, allthough the drop rate is a blind guess from the current data.
> DB: Added Soullocked Sinstone (pet)

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added the 9.0 mount [Silessa's Battle Harness](https://www.wowhead.com/item=183798/silessas-battle-harness). This mount can be obtained from a chest within the Broken Mirrors (Venthyr Travel Network rank 3).
> DB: Added Silessa's Battle Harness

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added yet another missing pet from 9.0. [Luminous Webspinner](https://www.wowhead.com/item=181171/luminous-webspinner) from a cache in Maldraxxus. No clue on the drop rate. I got it first attempt, but reports on wowhead says it's not 100%
> DB: Added Luminous Webspinner (pet)

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added another missing Shadowlands pet. [Stony's Infused Ruby](https://www.wowhead.com/item=183855/stonys-infused-ruby) from the Venthyr broken mirror system. Haven't personally been able to test this, as I don't have a venthyr, but seems pretty straight forward.
> DB: Added Stony's Infused Ruby (pet)

- Options_Defaults.lua
[Pommel Jewel of Remornia](https://www.wowhead.com/item=183395/pommel-jewel-of-remornia) has been confirmed dropping on LFR mode as well as normal difficulty. Added tracking for the missing mode.
> DB: Added LFR tracking for Pommel Jewel of Remornia

- Options_Defaults.lua
Added the achievement tooltips for [Mechagon](https://www.wowhead.com/achievement=13470/rest-in-pistons) and [Nazjatar](https://www.wowhead.com/achievement=13691/i-thought-you-said-theyd-be-rare) rares. As far as I can tell, this as all that's needed for this to function. Should in that case close #122
> DB: Added achievement tooltip for Mechagon/Nazjatar rares. Closes #122

- Options_Defaults.lua
Fixed attempts tracking for [Microbot 8D](https://www.wowhead.com/item=169385/microbot-8d) and [Golden Snorf](https://www.wowhead.com/item=169378/golden-snorf). These were being tracked in both heroic and mythic, but only drops in mythic mode. Also added UiMapIDs for both and added defeat detection. This also resloves #170 since this dungeon is no longer available in mythic keystone.
> DB: Fixed Mechagon dungeon pets. This resolves #170

- Options_Defaults.lua
Added achievement tooltip for shadowlands rares
- Adventurer of Bastion
- Adventurer of Maldraxxus
- Adventurer of Ardenweald
- Adventurer of Revendreth
- Better to Be Lucky Than Dead (The Maw)
> DB: Added achievement tooltip for shadowlands rares

- Options_Defaults.lua
I went over the full item-list (here #111) and adjusted the drop rates for several toys, pets and mounts so that they appear more correctly than when they were first implemented. I did not touch anything related to Island Expedition, as these have little accurate data.
Given that the mechagon items were fixed in #268 and #272 , the issue #111 can be closed.
> DB: Fix Rise of Azshara drop rates. Closes #111

- DB/Nodes.lua
- Locales.lua
- Options_Defaults.lua
Added the pet [Bottle of Gloop](https://www.wowhead.com/item=174456/bottle-of-gloop) which is obtained from fishing in BfA. This pet can only drop from fishing pools (Aberrant Voidfin School & Malformed Gnasher School) in the corrupted version of Uldum and Vale of Eternal Blossom. Both these two zones have different mapID's than the normal ones, and it appears that only these two types of fishing pools are available in these corrupted zones - thus making the tracking a lot easier than first thought. In sum: tracking that fishing is done in a pool in these two zones is enough.
This should close #158.
> DB: Added Bottle of Gloop. This closes #158

- Core/GUI.lua
Added NPC ID to tooltip if debug mode is enabled. This closes #99
This will ignore the setting to disable tooltip additions, I figured that made more sense.
[https://imgur.com/a/NmJ4eTO](https://imgur.com/a/NmJ4eTO)
> GUI: Added NPC ID to tooltip if debug mode is enabled.

- Core/GUI.lua
There is really no idea as far as I can tell as to why these should be clickable in the first place. The original Blizzard achievements open the Achievement frame and shows the new addition there, but these bogus toasts have no ties to that frame. As per now they either result in LUA erros or show a broken achievement frame. This should resolve #26.
> Made achievement toasts unclickable.

- Core/GUI.lua
- Locales.lua
- Modules/Options/Options.lua
- Options_Defaults.lua
Added functionality to configure and delay opening of the main tooltip. The option settings function just like the one to delay closing of the tooltip, but the logic to delay the opening is done with a call to Blizzard's function instead, as LibQTip don't support that.
This is bundled with the mouseover event, and has a default delay of 0.1 seconds.
This resolves #7.
> Tooltip configurable delay

- Core/EventHandlers.lua
- DB/Items/Pets/Shadowlands.lua
- DB/Nodes.lua
- DB/Spells.lua
- Locales.lua
Added tracking for Lucy's Lost Collar. This was a minor headache, because allthough the Dirty Glinting Object is registered as an NPC, the looting is different from any normal NPC. It uses a different opening spell (called "Looting") and it isn't cought by the normal methods. 
I had to add this as a special case. Rarity.isOpening is hardcoded to only accept spells translated to "Opening" and I didn't want to fake name this spell or expand those just to get past the checks. Detection is therefor similar to the one used for Mail Muncher in Horrific Visions. 
This closes #276.
> DB: Added Lucy's Lost Collar

- Core/Caching.lua
- Core/GUI.lua
- Modules/Options/Options.lua
Make a quick fix which should close #304. This makes the notification green if you are on the right faction and stays red when you are not. Found these in the main GUI as well as in the Options. Don't think these show up as NPC tooltips?
> Core: Made faction restriction colors more intuitive

- Core/EventHandlers.lua
This is not usually a problem, as most nodes are not colour coded (although I am not sure if any addons do modify this?).
However, with the addition of the Dirty Glinting Object, this produces an NPC tooltip. For some users, this will be colour coded and therefore it will not properly detect the attempt on Lucy's Lost Collar.
The colour coding will now be stripped if it does exist.
----------------
I'm not happy with where I placed the `StripColourCode` function? Any ideas for a more appropriate place?
Sorry if I haven't made myself clear in the commit/pull request message. I'll try to explain it a bit more if so.
> Strip the colour code from tooltip strings

- Core/EventHandlers.lua
- DB/Nodes.lua
- Locales.lua
Fixes the issue reported here: https://www.wowace.com/projects/rarity/issues/469
I also removed some duplicated locales and combined the events for the Forgotten Chest to check for both items at the same time.
> Forgotten Chest has a namesake in Stormsong Valley that should be ignored

- Core/GUI.lua
- DB/Mounts/BattleForAzeroth.lua
- Locales.lua
- Modules/Options/Options.lua
- Utils/DatabaseMaintenanceHelper.lua
In regards to the issue #203, I have added an option to check if any given world quest is currently active. This is then integrated into the existing holiday reminders, as a way of notifying players when certain items are obtainable. By flagging any relevant items with 'worldQuestId', the reminder should function just like the holiday ones, just with a different display text. If the linked world quest is not active, the item is marked as "Unavailable", and thus can also be hidden from the GUI if the option to hide unavailable items is checked. The option to enable/disable reminders on a specific item is also added on these items with 'worldQuestId'.
Currently I have only implemented the feature on one item; the Slightly Damp Pile of Fur from Dunegorger Kraulok (World boss in Vol'dun). …
> Added world quest "holiday" reminders

- DB/Mounts/BattleForAzeroth.lua
- Locales.lua
Added the mount [Ny'alotha Allseer](https://www.wowhead.com/item=174872/nyalotha-allseer) from Ny'alotha, the Waking City (BFA). Haven't added any defeat detection for this yet, but figured getting the tracking in sooner than later was more important. It'll be caught by the famous database verification tool eventually(!), so it won't be forgotten. This closes #231.
> Added Ny'alotha Allseer

- DB/Pets/HolidayEvents.lua
- DB/Toys/HolidayEvents.lua
- Locales.lua
- Utils/DatabaseMaintenanceHelper.lua
Added 5 missing items that are rewarded from the Stolen Presents during WInter Veil. This should be every missing items as far as I can tell, so should resolve #67.
EDIT: This does NOT contain the two illusions that can drop here
Added items:
- https://www.wowhead.com/item=128636	-- Endothermic Blaster
- https://www.wowhead.com/item=116456	-- Scroll of Storytelling
- https://www.wowhead.com/item=151349 -- Toy Weapon Set [Alliance]
- https://www.wowhead.com/item=151348 -- Toy Weapon Set [Horde]
- https://www.wowhead.com/item=90888	-- Special Edition Foot Ball
QuestIDs are best guess based on other items as this cannot be tested atm. Still better have potentially broken 'defeat detection' than no tracking at all.
Also went over the other items that are contained in this present and made …
> Added missing items from Winter's Veil gifts + fixed couple old ones

- Core/EventHandlers.lua
- DB/Nodes.lua
- DB/Pets/Shadowlands.lua
- DB/Spells.lua
- Locales.lua
Added the [Gilded Wader](https://www.wowhead.com/item=180866/gilded-wader). Once finished, this closes #278.
Status:
There are multiple reports of various other nodes also dropping this pet besides the ones listed on Wowheads 'contained in'. I have not added tracking for any of those at this moment. That is because allthough I don't doubt the wowhead comments, there just aren't any screenshots or other proof to verify these nodes to drop the pet. Mostly there is just a single report on any given source. I am leaving the others until someone can prove them.
Reported but not confirmed:
```
[Penitence of Purity] in Bastion (Kyrian only)
[Greed's Desire] Crypt of the forgotten, Revendreth
[Runebound Chest] Maldraxxus
[Stoneborn Satchel] Revendreth (has a vague screenshot)
[Pugilist's Prize] …
```
> Added Gilded Wader (pet)

- DB/Mounts/Cataclysm.lua
- DB/Mounts/Legion.lua
- DB/Mounts/MistsOfPandaria.lua
- DB/Mounts/WarlordsOfDraenor.lua
- DB/Mounts/WrathOfTheLichKing.lua
- DB/Pets/Classic.lua
- DB/Pets/MistsOfPandaria.lua
- DB/Pets/TheBurningCrusade.lua
- DB/Pets/WrathOfTheLichKing.lua
I've gone over the list of items available on the Black Market Auction House and I've added `blackMarket = true` to all relevant items in the database where this was missing. This closes #335.
> Added missing BMAH tag to items

- DB/Toys/Shadowlands.lua
As the title says, I just added defeat detection to [Battlecry of Krexus](https://www.wowhead.com/item=184318/battlecry-of-krexus)
> DB: Added defeat detection to Battlecry of Krexus

- DB/Mounts/Shadowlands.lua
Here comes more missing detection. This time the Venthyr only rare mount [Hopecrusher Gargon](https://www.wowhead.com/item=180581/hopecrusher-gargon).
> Added defeat detection to Hopecrusher Gargon

- DB/Toys/WarlordsOfDraenor.lua
As per title, I have been grinding [this stupid toy](https://www.wowhead.com/item=122304/fandrals-seed-pouch) and decided to add the defeat detection along the way.
> DB: Added defeat detection for Fandral's Seed Pouch

- DB/Pets/Shadowlands.lua
- Locales.lua
This PR includes the following pets from the 9.1 patch
> 
> * [X]  https://www.wowhead.com/item=186555/eye-of-extermination
> * [X]  https://www.wowhead.com/item=186554/eye-of-allseeing
> * [X]  https://www.wowhead.com/item=186541/mosscoated-hopper
> * [X]  https://www.wowhead.com/item=186552/rook
> * [X]  https://www.wowhead.com/item=186558/irongrasp
> * [X]  https://www.wowhead.com/item=186557/fodder
> * [X]  https://www.wowhead.com/item=186550/mawsworn-minion
> * [X]  https://www.wowhead.com/item=186449/amaranthine-stinger
> * [X]  https://www.wowhead.com/item=186534/gizmo
> * [X]  https://www.wowhead.com/item=186547/invasive-buzzer
> * [X]  https://www.wowhead.com/item=186564/golden-eye
> * [X]  https://www.wowhead.com/item=186546/copperback-etherwyrm
> * [X] …
> Add tracking for (the majority of) pets that were introduced in patch 9.1

- DB/Mounts/Shadowlands.lua
- DB/Toys/Shadowlands.lua
- Locales.lua
Further research points that this mount is obtained from a quest reward rather than dropping from the NPC. Added the quest item to the database instead, similar to the Necrolord and Venthyr one.
Video proof: [https://www.youtube.com/watch?v=7MN3dM5NFlI](https://www.youtube.com/watch?v=7MN3dM5NFlI)
> DB: Added Intact Aquilon Core and removed Foresworn Aquilon

- Core/EventHandlers.lua
- DB/Nodes.lua
- DB/Toys/Shadowlands.lua
- Locales.lua
As advertised in the title, I have added the two toys found in Zooval's Vault in the rift phase of the maw.
[https://www.wowhead.com/item=187113/personal-ball-and-chain](https://www.wowhead.com/item=187113/personal-ball-and-chain)
[https://www.wowhead.com/item=187416/jailers-cage](https://www.wowhead.com/item=187416/jailers-cage)
This PR closes #361
> DB: Added the two toys from Zooval's Vault

- DB/Mounts/Shadowlands.lua
With todays [hotfix](https://worldofwarcraft.com/en-gb/news/23691036/hotfixes-july-15-2021), Fallen Charger has a new drop rate of about 15%
> DB: Updated drop rate for Fallen Charger

- Core/EventHandlers.lua
- Core/Profiling.lua
- Locales.lua
- Modules/Options/Options.lua
Extracted the relevant parts from #398 
There are two main features (related) here:
* A streamlined ``Profiling`` API that supports nested groups, inspired by the profiling parts of the ``console`` API in browser environments
* An addition to the Options UI that allows accessing and resetting the profiling data
> Add streamlined Profiling API

- Utils/Sorting.lua
Extracted from #409  to avoid the headache with rebasing to the various branches.
> Use the builtin table.sort (quicksort) instead of the slower selection sort algorithm that's currently used by default

- DB/Toys/Shadowlands.lua
- Locales.lua
It's long overdue, but I finally added the [Adamant Vaults Cell](https://www.wowhead.com/item=187417/adamant-vaults-cell) from Adamant Vaults in Torghast. Luckily the bosses seem unique to this particular subzone, so no fancy logic was required. This closes #360.
> Added Adamant Vaults Cell

- DB/Pets/Shadowlands.lua
- Locales.lua
Added another easy one. [Gilded Darknight](https://www.wowhead.com/item=186549/gilded-darknight), a pet from Adamant Vaults in Torghast. This closes #366 :)
> Gilded Darknight

- DB/Toys/Shadowlands.lua
- Locales.lua
Added the toy [Shaded Judgment Stone](https://www.wowhead.com/item=187174/shaded-judgment-stone). As mentioned in the issue #359, this item has been a bit buggy in the beginning of the patch, but does now drop - but Wowhead data is likely affected by the late and buggy appearance. Added the confirmed sources with a guesstimate droprate.
This closes #359.
> Add tracking for Shaded Judgment Stone

- DB/Toys/Shadowlands.lua
[Bottled Shade Heart](https://www.wowhead.com/item=187139/bottled-shade-heart) was added with 1% drop as it had little recorded data at the time. Drop rate is more like 12%, so updated to reflect this
> Adjusted drop rate for Bottled Shade Heart

- DB/Mounts/BattleForAzeroth.lua
As per title, [Sharkbait's Favorite Crackers](https://www.wowhead.com/item=159842/sharkbaits-favorite-crackers) is easily soloable by anyone these days, so removed groupSize and equalOdds on it
> Flagged Sharkbait's Favorite Crackers as soloable

- DB/Toys/Shadowlands.lua
[Smolderheart](https://www.wowhead.com/item=180873/smolderheart) was listed with 4% drop - Wowhead says 5%. Small annoyance, but fixing as I am grinding it atm
> Adjusted drop rate for Smolderheart

- DB/Mounts/WarlordsOfDraenor.lua
Updated Infinite Timereaver bosses that were updated for 9.1.5 that had some dungeons rotate out and others in for previous TW events.
> Update the list of NPC IDs for the Infinite Timereaver mount

- Core.lua
- DB/Item.lua
- DB/Mounts/Shadowlands.lua
- Locales.lua
Finally got around to looking at this again, and with the new information presented, I have implemented tracking for this badboy. Getting a valid attempt requires having a quest flagged as completed, as this represents having the companion active.
This closes #343.
> Added tracking for Bonehoof Tauralus

- Core/GUI/MainWindow.lua
This will flag covenant items that the player can't currently obtain as "unavailable", similar to how items from other sources are treated.
--
It's #451 but with a different commit message and subject line.
> GUI: Corrected the availability status display for covenant items

- DB/Mounts/BattleForAzeroth.lua
[Mummified Raptor Skull](https://www.wowhead.com/item=159921/mummified-raptor-skull) is soloable after the changes to legacy loot for BFA dungeons. Removed the groupSize etc for this.
Also added defeat detection while I was at it
> Updates for Mummified Raptor Skull

- DB/Mounts/BattleForAzeroth.lua
[Underrot Crawg Harness](https://www.wowhead.com/item=160829/underrot-crawg-harness) is soloable after the changes to legacy loot for BFA dungeons. Removed the groupSize etc for this.
Also added defeat detection while I was at it
> Updates for Underrot Crawg Harness

- .github/workflows/publish-release.yaml
- .pkgmeta
- Rarity.toc
This replaces the Webhooks-based workflow, since it doesn't support platforms other than CurseForge.
> Set up GitHub Actions workflow to publish releases via the BigWigs packager

- DB/Nodes.lua
I've added the nodes `Mawsworn Supply Chest` and `Sandworn Chest` which was missing from the last release. Not sure if there are any others missing at this point, but these two has been causing issues
> Added missing nodes

- Core/Interoperability/TradeSkillMaster/AuctionDB.lua
That's clearly an oversight/rookie mistake. It must have been many years since I wrote that code, though I remember making this particular mistake before...
Anyway: Seems like luacheck recently added the capability for detecting this type of error, so the CI is now failing (as it should)!. However, my local version was outdated and subsequently didn't raise the issue, which is why it went unnoticed for so long.
> Fix an incorrect negation in the TSM module

- .github/workflows/check-format.yaml
Apparently GitHub completely removed support for standard git protocols, and luarocks can no longer download the formatter as a result.
Edit: Resolved by using a more recent luarocks version in the workflow.
> Update the luaformat workflow to fix a git protocol error

- DB/Mounts/Legion.lua
Following up on a previous Discord conversation and decided to add another one of the missing defeat detections from Legion raids, Living Infernal Core. Also added a missing tooltipNPC while I was at it. Did a quick run-through and seems to work just fine
> Living infernal core updates

- Core/GUI/GameTooltipHooks.lua
Allows Rarity info to be shown on GameTooltips from Quest Givers and the Quest Log. Moved the code that handles the Quest Reward to a reusable function.
Questgiver:
Quest Log:
At the bottom I left commented out code for Emissaries. Currently the text is injected above the Quest Item so I leave it to you to finish that if you wish to use it:
> Add GameTooltip hooks for Quest Rewards

- .github/workflows/publish-release.yaml
This is clearly an oversight; instead of skipping the release for non-tagged versions the workflow will always execute the final step (skipping the checkout). Thankfully it didn't publish any releases on accident, because there's no code to publish, but it's definitely a silly mistake to make.
> Fix the tagged versions check in the release workflow

- DB/Pets/MistsOfPandaria.lua
According to https://www.wowhead.com/item=104159/ruby-droplet the drop rate is 3% not 4%.
> Update the drop rate of Ruby Droplet

- Core/EventHandlers.lua
This event has been removed entirely. Using CURSOR_CHANGED instead appears to be working in a similar fashion, though more testing is needed.
> Fix OnCursorUpdate event handling to account for 10.0 changes

- Modules/Options/Rarity_Options.toc
- Rarity.toc
This is a cosmetic change, fixing the "addon out of date" pseudo-errors that tend to confuse people.
> Update the TOC interface version to 10.0

- Core.lua
- Core/Detection.lua
- Core/EventHandlers.lua
- Core/GUI/GameTooltipHooks.lua
No guarantees that something "hidden" isn't still broken, since it's infeasible to test everything. I also completely ignored the tooltip scanning changes since the old approach should still work - migrating that to the ``C_TooltipInfo`` APIs would be a separate issue.
> Fix various script errors caused by 10.0.2 API changes

- Core/Detection.lua
I missed the return value change in #503, which means inventory scanning is even more broken than it already is (see #500).
> Fix usage of ContainerItemInfo return values

- Core/GUI/GameTooltipHooks.lua
The first part is an oversight (presumably) and should've fixed long ago.
The second part is a hack to work around errors reported by some players. I think it's due to other addons interfering by creating tooltips that don't use the new APIs, or at least aren't using them correctly (?). This is of course a bit of an assumption since I don't know what's going on and I can't reproduce the issue either. Ideally it would fix the problem by ignoring those tooltips, but realistically "anything can happen" and it will have to be adjusted again later (when more information is available).
> Adjust early exits in the GameTooltip script handler to hopefully fix some more errors

- Core/GUI/GameTooltipHooks.lua
Whenever another addon makes use of a tooltip (frame that inherits GameTooltipDataMixin), multiple calls of the post-hook can add duplicate lines to the global GameTooltip.
I still can't test this since the issue doesn't manifest for me, but it should prevent this particular problem IFF my assumptions are correct. And if they aren't... well, then this is just useless but not actively harmful.
See discussion in #506 and on WowAce/Discord.
> Add another early exit condition to eliminate tooltip hooks executed for third-party tooltips

- .luacheckrc
- Core/GUI/MainWindow.lua
Blizzard has apparently replaced the magic global with a proper CVar.
> Update the floating combat text detection (to use CVars instead of magic globals)

- .luacheckrc
- Core/EventHandlers.lua
- DB/Mounts/Dragonflight.lua
- DB/Nodes.lua
- DB/SharedConstants.lua
- Locales.lua
After reading through the discussion on #515 I decided to take a shot at solving it. 
PR includes the faction ID's for the 4 main dragonlflight factions, as well as handling tracking for the Verdant Skitterfly mount. Tested with a couple toons on various renown level to verify.
If merged this closes #515. :)
> Added tracking for Verdant skitterfly

- Core/EventHandlers.lua
This is a more appropriate event for handling completions than CURRENCY_DISPLAY_UPDATE.
> Move handling of artifact completions from CURRENCY_DISPLAY_UPDATE to RESEARCH_ARTIFACT_COMPLETE

- .github/check-interface-versions.sh
- .github/workflows/check-toc-version.yaml
- Modules/Options/Rarity_Options.toc
- Rarity.toc
The interface version is perpetually out-of-date since it's so easy to forget. This causes the client to warn users, which in turn create issues or bug reports. Presumably, having an automated check in place will make it easier to remember?
> Add an automated check for outdated TOC interface versions

- Locales.lua
- Modules/Options/Options.lua
The "disable for classes" option couldn't be set for Evokers previously.
> Add Evoker to the list of recognized classes

- CHANGES.MD
- Changes.lua
The DF update is half-finished, but all of the important mounts should be in, and the pets/toys can be added piecemeal I suppose.
> Update the changelog for r719

- DB/SharedConstants.lua
- DB/Toys/Dragonflight.lua
- Locales.lua
It's not a real mount, so I just added it as an item (similar to eggs).
> Add tracking for Reins of the Quantum Courser

- Core/GUI/MainWindow.lua
Instead of prepending Rarity to the waypoint name, it seems cleaner to use the TomTom API's "from" field. Maybe that's a recent addition? Either way, it de-clutters the waypoint title a little bit and fixes the  "From: ?" part. No big deal.
Before:
After:
(Ignoring the extra name, since I forgot to add this in the first screenshot)
> Set Rarity as the source for created TomTom waypoints

- DB/Pets/MistsOfPandaria.lua
It seems that the level squish changed the drop table of several relevant NPCs. Any that are now level 30 seem to no longer drop MOP items, and wowhead comments as well as a user report (15k attempts, not a single drop) suggests that the pet cannot be obtained from them at this time.
It's certainly possible that the pet does drop from level 30 enemies after all, but knowing Blizzard I'd rather err on the side of caution and avoid people wasting their time killing these NPCs.
While looking into the report I also noticed an NPC was missing, so I've added that one while I'm at it.
---
See also: https://www.wowace.com/projects/rarity/issues/521
> Update the NPC list for Gahz'rooki's Summoning Stone

- Core/EventHandlers.lua
- DB/Toys/Dragonflight.lua
- Locales.lua
adding Everlasting Horn of Lavaswimming toy. Too get a more accurate tracking on this toy you would have to track the event completion but for now its tracked by killing the mob "Inferna the Bound" at the end of the event "Siege on Dragonbane Keep".
> Add Everlasting Horn of Lavaswimming (toy) to the database

- DB/Pets/Dragonflight.lua
- DB/Toys/Dragonflight.lua
Clearly an oversight, which should've been caught by automated tests...
> Fix various waypoint labels for Dragonflight collectibles

- DB/Mounts/Shadowlands.lua
Not sure if this was always sold by a vendor, but now it is.
> Add a sourceText to Armored Bonehoof Tauralus

- Core/Database.lua
- Core/GUI/GameTooltipHooks.lua
- Tests/test-database.spec.lua
- Tests/unit-test.lua
As a follow-up to the attempts detection fix, the UI should reflect that the item can't be obtained by players of the opposite faction.
Example: Time Rift boxes display the Horde mount (wolf) on Alliance, but opening the box correctly doesn't add the attempts. That'll be quite confusing and it's best to just hide the item for Alliance players.
---
Follow-up to #612
> Fix the tooltip for faction specific container items

- DB/Mounts/Shadowlands.lua
- Locales.lua
Follow-up to #615 - looks like all of the mounts were added to a vendor after the fact.
> Add a sourceText to the remaining covenant-specific vendor mounts

- Core/EventHandlers.lua
- Core/Session.lua
Much cleaner, simpler, and more reliable. The timeout is still adjustable so nothing should have been lost.
> Replace the LOOT_READY session lockout with a bucketed event handler

- Core/EventHandlers.lua
- luacheckrc.lua
10.x added new events to handle open/close frames for many game UI frames—things like the guild/bank, the auction house, and the mailbox. The old events still exist; some actions trigger both old and new events, some trigger only the old event, and some only trigger the new event. (Most likely, more events will cut over from old to new in future game releases.)
This adds EventRemapping to basically convert new style events to old style events, allowing existing event handler code to work with either type of event.
Most notably here, the MAIL_CLOSED event no longer fires when leaving the mailbox; this left Rarity thinking the player is at the mailbox, so it would ignore loot events.  After EventRemapping, Rarity sees "MAIL_CLOSED" again, hopefully fixing a longstanding issue where loots …
> Fix no loot tracking after using mailbox

- Core/EventHandlers.lua
There have been reports of the latest loot handling change causing attempts to not be registered. After some investigation, it turns out that certain "fast loot" addons exist that basically spam-loot via LootItem API on LOOT_READY. Examples of these are AutoLootPlusPlus and ElvUI_WindTools/FastLoot
Both of them cause the LOOT_OPENED event to not be triggered, which means Rarity won't trigger OnLootReady either - or at least not reliably. Since we used only LOOT_READY before, there's probably no reason to rely on LOOT_OPENED as long as the detection is working fine (and spam-opening containers doesn't fail).
If this causes problems for regular users it should be rolled back.
> Fix OnLootReady handling with 3rd party loot addons

- DB/Toys/Dragonflight.lua
- Locales.lua
It seems that the drop rate is questionably low and no information about this item was made available by Blizzard. Since I don't want to have people try and farm this repeatedly thinking they'll get it in 40 attempts, let's make it very clear that that the drop rate might be abysmal. Hopefully, this will prompt some research so people can make a more informed decision, or postpone farming this until more data has been gathered by the community.
In the same vein, using the weekly quest for defeat detection makes the most sense, to discourage players from repeatedly farming it (without doing more research first, that is). And to be even clearer, I'll also adjust the sourceText, although it may have to be updated again later should we get better info on this thing.
> Update DB entry for Everlasting Horn of Lavaswimming

- Core/EventHandlers.lua
- Core/Session.lua
As is evident from the various looting-related bug reports, "fast loot" addons still break Rarity's NPC detection method - even with the latest changes. I suspect this is due to how AceEvent handles the aggregated LOOT_READY triggers: By the time we're notified the fast loot addon has already taken all the loot, so Rarity can't see anything (and thus won't add any attempts).
This should be largely identical to the previous implementation, the only change being that the delay is now configurable (through code only, for now). If spam-opening containers becomes a significant concern, the delay could be exposed to the config UI to allow users to adjust it so that attempts are no longer failing to be detected.
Obviously, this is sub-optimal as ideally we'd be able to handle both scenarios …
> Re-introduce the session locking mechanism

- DB/Pets/HolidayEvents.lua
- DB/Toys/HolidayEvents.lua
Now that there's a shared constant, might as well use it.
> Replace hardcoded map IDs for Darkmoon Island

- CHANGES.MD
- Changes.lua
Bit late for the Darkmoon Faire fix, but the TOC version has changed and the addon is now being displayed as "outdated" again.
> Update the changelog for r723

- Core/Collections.lua
At some point they must have changed; the old ones are now invalid.
This could lead to pets not being processed and marked as found? (#632)
> Update the pet journal flags passed to SetFilterChecked

- .luacheckrc
- Core/EventHandlers.lua
- Core/GUI/ScrollingDebugMessageFrame.lua
- README.MD
- Rarity.toc
- Utils/DebugCache.lua
It doesn't look great, but it's workable. Basic functionality only:
* Messages are automatically synchronized (pushed) by the debug cache
* A button exists to copy/paste everything in the log (yes, it's tiny... I was unable to make it bigger without breaking the UI)
* Another button exists to clear the debug log (cache and scroll frame contents)
* Individual portions of the log can also be copied manually (via mouse) - this is a bit wonky due to how scroll frames work?
* The window can be closed, although currently not by pressing ESC
* It also can't be moved or resize and doesn't have a title bar
Note: I repurposed the `/rarity dump` command since this does the same thing, only better. Might need renaming (later)?
If someone who knows more about the UI system than me wants to improve it, …
> Create a UI window (scrolling message frame) to more easily manage cached debug messages

- DB/Spells.lua
Add Spell ID for the scavenging by engineers so that the scavenging of a tracked NPC would not count as an attempt.
Tested against Arachnoid Harvester.
Also tested that the scavenging spell ID is the same in different zones.
Fixes #644
> Add the spell ID for Scavenging (Engineering) to the database

- Bindings.xml
- Core.lua
- Locales.lua
I can't seem to figure out why setting the header doesn't work if using the default ADDONS category, so I guess there will just be one more category for people to scroll past... Oh, well.
> Register a new keybind to toggle the debug UI

- Core.lua
- Core/Caching.lua
- Core/EventHandlers.lua
- Core/GUI/MainWindow.lua
When an item is disabled for the player's class, attempts are successfully blocked (via `IsAttemptAllowed`). However, the alert may still trigger when any such item is added to the inventory, in which case the item would be incorrectly "checked off" (untracked).
> Prevent alerts from triggering for class-filtered items

- Bindings.xml
Reported on Discord by michael (mikuhl_). Thanks!
`_G.Rarity` "accidentally" works because AceAddon adds a `__tostring` metamethod, but it's not the right way to get there obviously.
> Fix the keybinding category in Bindings.xml

- DB/Toys/Dragonflight.lua
This should work in Mythic+ keystone dungeons as well, or at least that's how the BFA mounts are configured.
> Add kill statistics for Reins of the Quantum Courser

- DB/Toys/Dragonflight.lua
Adds the missing defeat detection settings and should now prevent attempts on Heroic difficulty, as wowhead says it's Mythic-only.
> Update the database entry for Reins of the Quantum Courser

- Core/EventHandlers.lua
Without tests this unfortunately slipped past the PR review. My bad.
> Fix the detection for Dreamseed Cache mounts

- DB/Toys/HolidayEvents.lua
- Locales.lua
According to wowhead, these 2022 Winter Veil rewards are now obtainable from Stolen Presents... As is tradition?
> Added Falling Star Flinger and Falling Star Catcher (toys)

- DB/Mounts/Dragonflight.lua
- Locales.lua
This also seems to be obtainable from containers, but the addon doesn't currently support multiple sources for a single item.
Will have to look into that eventually, but having the dig site boss be tracked is likely better than no tracking at all.
> Add Clayscale Hornstrider (mount) to the item database

- DB/Toys/Dragonflight.lua
The boss appears in two dungeons, and this statistic is for the alternate version (which doesn't drop the mount). Unfortunately, there's no statistic for the "right" version that could be used.
This fixes the tracking for Quantum Courser, which has been reported as broken by multiple people. It seems that I originally added the wrong statistic because wowhead didn't display the dungeon name? Or maybe I misread, who knows.
> Remove the statistic ID for Quantum Courser

- Core.lua
Resolves #706. This coincidentally also works in cases where mobs are kept alive and pockets "respawn" after some time.
> Prevent Pick Pocket from blocking regular loot events

- Core/Interoperability/Blizzard/AddonCompartment.lua
- Rarity.toc
Resolves #660. Improvements can be made later, for now this is behaving the same way as the default `/rarity` slash command.
> Register the options UI with Blizzard's Addon Compartment

- Core.lua
- Core/Interoperability/Blizzard/AreaPOIs.lua
- DB/Pets/Dragonflight.lua
- Rarity.toc
This approach has two limitations/issues; see commit messages for details. They aren't critical, so this can already be merged.
1. Elementals that persist after the storm has ended won't add attempts unless their storm event is currently active
2. The event is detected mapwide, so technically all sites will be "enabled" (and add attempts) while it's active
I think the first issue can probably be ignored, and the second may warrant a second look if it turns out to be a problem (later).
> Implement Area POI handling for Elemental Storm events

- Core.lua
When an item doesn't require active Area POIs, which is the case for almost all items in the database, the field should simply be ignored. The code currently specifies that attempts should be disallowed in this case, which is clearly wrong (and I missed it).
I think the reason for this is somewhat poor naming of `HasActiveAreaPOIs` - it detects whether the current map has active area POIs AND whether the given list of POIs contains an entry that is currently active. This is arguably not immediately obvious, but there are other issues that need fixing also. Might need a rework the POI code to fix #721 (deferred for now).
> Fix an oversight in the Area POI detection

- DB/Pets/BattleForAzeroth.lua
Same as the mounts that have already been moved.
The raids are reportedly now solo-able, so there's no need to keep raid drops in this category.
> Move all BFA raid pets to the regular pets group

- DB/Toys/BattleForAzeroth.lua
These were reported to be easily solo-able now, as well.
> Move Arathi world boss drops to the regular pets category

- DB/Mounts/BattleForAzeroth.lua
- DB/Mounts/Shadowlands.lua
As requested on Discord. Not tested ingame, but unless the encounter name from wowhead is incorrect it should "just work".
> Add lockout details for several legacy mounts

- DB/Mounts/Shadowlands.lua
The name displayed by wowhead doesn't match the one used ingame.
> Fix the encounter name for Vengeance's Reins

- Core/GUI/MainWindow.lua
As requested on Discord, this allows toggling the main window when setting an auto-hide delay of zero ("forever"), but only when using clicks to activate the window. In hover mode there's no way to hide the window again, so the original fallback was kept.
> Add support for zero length auto-hide delays

- .luacheckrc
- Core.lua
- Core/Announcements.lua
- Core/EventHandlers.lua
- Core/GUI.lua
- Core/GUI/DataBrokerDisplay.lua
- Core/GUI/FauxAchievementPopup.lua
- Core/GUI/GameTooltipHooks.lua
- Core/GUI/MainWindow.lua
- Core/Init.lua
- Core/Interoperability/Blizzard/AddonCompartment.lua
- Core/Interoperability/TradeSkillMaster/AuctionDB.lua
- Core/Interoperability/WoWUnit/Testing.lua
- Core/Profiling.lua
- Core/Session.lua
Moved depreciated API calls to the relevant systems and updated to the new [Settings System](https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes) for the mini-map icon to open to the settings category directly.
> Update for 11.0.2

- .github/check-interface-versions.sh
- Modules/Options/Rarity_Options.toc
- Rarity.toc
Piling more hacks onto this sketchy script, it now extracts the highest (latest) version number if there are multiple listed.
I don't expect the approach to be any less brittle, but at least it should again function as an alert in case of outdated TOC versions.
> Enable the TOC version check script to process comma-separated lists

- .github/workflows/check-format.yaml
V2 triggers a deprecation warning in the GitHub UI.
> Upgrade the format check to use stylua-action v4

- Modules/Options/Rarity_Options.toc
The ingame menu currently displays a default "question mark" icon. For consistency, use the same icon as the core addon.
> Add an IconTexture for the Options module

- Modules/Options/Options.lua
- Modules/Options/Rarity_Options.toc
- Rarity.toc
Removes ancient optional dependency to manage loading the options, blizzard allows addons to set a LoadOnDemand field in the toc for this.
> Migrate the Options module from AddOnLoader to LoadOnDemand

- Core/EventHandlers.lua
- DB/Mounts/TheWarWithin.lua
- DB/Nodes.lua
- Locales.lua
Apparently these drop Machine Defense Unit 1-11 on live servers, which used to be listed as an achievement reward.
> Add tracking for Awakened Caches

- DB/Mounts/Dragonflight.lua
- DB/SharedConstants.lua
- Locales.lua
This used to be a guaranteed drop on Mythic difficulty, but is now another 1% rare mount just like the others.
> Add Anu'relos to the item database

- Core/GUI/GameTooltipHooks.lua
- Locales.lua
- Modules/Options/Options.lua
- Options_Defaults.lua
> Add an option that allows hiding untracked items from tooltips

- DB/Mounts/TheWarWithin.lua
Nerub-ar Palace is a raid, not a dungeon. Copy/paste error?
> Remove the difficulty setting for Sureki Skyrazor

- DB/Toys/Legion.lua
- DB/Toys/WarlordsOfDraenor.lua
They need to be excluded so that attempts don't register.
> Fix up disableForClass entries for Dracthyr Evokers

- .pkgmeta
That's clearly an oversight. What would players even do with them?
> Exclude test files from published releases

- .pkgmeta
Dot files are always ignored by the packager and needn't be listed.
---
From the [CurseForge docs](https://support.curseforge.com/en/support/solutions/articles/9000197952-preparing-the-packagemeta-file#Ignoring-folders-or-files):
> Files beginning with a period, like .pkgmeta and .docmeta, are always ignored by the packager and should not be listed here.
> Remove the redundant .pkgmeta ignore list entry for .luacheckrc

- .github/workflows/unit-tests.yaml
GitHub updated the `ubuntu-latest` tag so that it now points to `ubuntu-24.04`. There's no release of the Lua runtime that's built using the updated system libraries yet (nor is it needed here). This should fix the CI failures at least.
> Pin the unit test workflow to ubuntu-22.04

- Utils/PrettyPrint.lua
With `PP:FormatTime` all times were being returned as "0:00" since the "self" argument was missing, and all times would appear as `nil` for the `t` argument, causing the 
```lua
if not t then
return "0:00"
end
``` 
code to always run.
Particularly, this fixes the empty "Time" column in the main display.
> Fixing wrong syntax for utility function FormatTime

- Core/EventHandlers.lua
This is an isolated change extracted from #808 (co-authored by @aSnejbjerg). For more context, see:
* https://github.com/aSnejbjerg/RarityClassic/issues/5
* https://github.com/aSnejbjerg/RarityClassic/pull/7
* https://warcraft.wiki.gg/wiki/Patch_10.0.0/API_changes#Interaction_Manager
* https://warcraft.wiki.gg/wiki/PLAYER_INTERACTION_MANAGER_FRAME_SHOW
* https://warcraft.wiki.gg/wiki/PLAYER_INTERACTION_MANAGER_FRAME_HIDE
Note: According to the above lists, there are some other events that should probably also block inventory changes. These aren't included here. Examples would be void storage, Warband bank, or any other feature that could modify inventory items.
(It might even be sensible to block on all interactions, as new ones might be added and the list needs to be updated?)
> Simplify the handling of player interaction events

- Core/EventHandlers.lua
Forgot to remove those earlier. With PLAYER_INTERACTION_MANAGER_FRAME_SHOW and PLAYER_INTERACTION_MANAGER_FRAME_HIDE, there's no need for them any more.
> Removed RegisterEvent calls for the now-unused legacy player interaction events

- .github/check-interface-versions.sh
- Modules/Options/Rarity_Options.toc
- Rarity.toc
- Tests/Fixtures/Test.toc
- Tests/TOC/BlizzardTOC.lua
- Tests/TOC/CDN.lua
- Tests/test-toc.spec.lua
- Tools/check-cdn-version.lua
With this, it should be possible to manage all three WOW product lines (Retail, Cata, Classic Era) with just one TOC file.
(Technically this flags the addon as compatible with classic clients even if the necessary changes aren't merged yet)
> Upgrade the CDN version check (and related tools) to support multiple TOC interface versions

- Core/Collections.lua
- Core/Detection.lua
- Core/EventHandlers.lua
- Core/GUI/GameTooltipHooks.lua
The tooltip hooking functionality is going to be disabled, which isn't ideal. It should be possible to adapt the original retail code and make both methods work alongside each other. Since I don't have time to look into that right now and it's probably not a critical issue (at least for the next release), I'll leave it for later. Classic Era likely needs more work in general.
> Fix various script errors on Classic Era realms

- Options_Defaults.lua
This used to be the standard option in LibSink, but since Blizzard's UI revamp in 10.0, LibSink falls back to the floating combat text instead. There have been numerous reports of people not liking this change, or in some cases even being unable to see announcements at all. They will usually blame Rarity and/or be confused by the lack of selected output channels.
---
Resolves #820 .
> Explicitly set ChatFrame as the default output sink

- Modules/Options/Options.lua
No need to disable the actual group, as that would be annoying if it then later becomes available.
There's no items being exported to those groups anyway, so hiding the checkbox should be sufficient.
---
Resolves #817.
> Hide expansion toggles for categories that aren't yet available

- .pkgmeta
Support for the obsolete and unmaintained AddonLoader tool was dropped in favor of Blizzard's equivalent system (see #752). WowAce still lists it as a dependency because this entry wasn't removed, though.
> Remove the addon-loader entry from .pkgmeta

- DB/Toys/HolidayEvents_BattleForAzeroth.lua
This typo was fixed when splitting the holiday items database (in b2b1f3063e27160ac8114bde6dc55b2d50532b30), but previous attempts would have been stored under the old (incorrect) name. I don't have time to refine the WIP migration PR (#824) before the next release, so it's probably better to restore the original name for the time being, and take all the time needed to fix the database up properly later.
Players will only see the localized name, which doesn't contain the typo. Fixing the name is of moderate utility at best and can be deferred. I'd rather not merge a half-baked DB migration feature before I've spent more time on refining and testing it.
> Restore the original name for Crashin' Thrashin' Battleship

- .pkgmeta
- Core.lua
- Rarity.toc
This function hasn't been used, or even referenced, since at least 2018.
---
Before merging: Review SVN history to see why it was added (see https://en.wiktionary.org/wiki/Chesterton's_fence)
---
Tracing back the commits:
* `GetDistanceToItem` first appears in a9595831a9726a45f5103da711f317a4014b6da0 (introduces sorting by zone)
* The function isn't used by this sort method, which [still exists in the code](https://github.com/WowRarity/Rarity/blob/b097671102a599286ed7be613c627cd762cce4d6/Utils/Sorting.lua#L116-L151)
* There's apparently been no change to the implementation after that point
* Checking out the last SVN snapshot (f0aa6a7), there are 30 tags with this function included
* There's however not a single use, so it was probably an experiment (sort by proximity)
Given that the …
> Remove GetDistanceToItem and Libs/HereBeDragons-2.0

- DB/Mounts/TheWarWithin.lua
Required for the defeat detection.
> Add a lockBossName value for Sureki Skyrazor

- Core.lua
- Core/EventHandlers.lua
- Core/GUI/DataBrokerDisplay.lua
- Core/Interoperability/Blizzard/AddonCompartment.lua
- Locales.lua
- Modules/Options/Options.lua
With fallback in case they're disabled. There's no way this is 100% robust - there are too many failure states to manually test.
Either way, it should make it easier to see that the options are disabled and to load them directly inside the settings UI.
Also resolves #762 by registering the fallback UI + options tree in the core addon, lazy-loading the full UI as needed.
> Enable deferred loading of the Options module

- Core/GUI/GameTooltipHooks.lua
The original code used item links, but that doesn't seem to be required with the new `TooltipDataProvider` system. AFAICT the handling now doesn't work at all for containers, since they don't provide a hyperlink property.
Maybe I've missed some API changes? Either way, this should work for containers in the inventory at least.
---
Resolves #746.
> Fix early exit conditions for ItemRefTooltip hooks

- Core/GUI/GameTooltipHooks.lua
There are two tooltip hooks, and `onTooltipSetUnit` checks for different conditions than `onTooltipSetItem`.
This setting therefore only hides the tooltip text for units, but not for container items.
---
Resolves #525.
> Skip ItemRefTooltip hooks when they're globally disabled

- Core/Collections.lua
- Core/Debugging.lua
- Core/Detection.lua
- Core/EventHandlers.lua
- Core/GUI/DataBrokerDisplay.lua
- Core/GUI/MainWindow.lua
- Core/Tracking.lua
Same thing, but (with some overhead) can aggregate the results and inspect them more easily. I quickly put this together to get more data on the combat log event handling, so this could surely be refined. It's not that important, though.
(Also decoupled profiling output from the profiling setting to reduce spam if debug mode is disabled)
New hooks have been added for some event handlers as well; they don't seem to incur significant overhead, though.
> Replace debugprofile calls with (mostly) equivalent Profiling API uses

- Core/Announcements.lua
When an item has already been obtained, only the current run of attempts should be considered to determine "luckiness".
That is to say, once you find an item the percentage should be reset and not "remember" the total attempts count.
This behavior is consistent with the way that the LDB and main window counterparts work, as well as player expectations.
> Fix the luckiness calculation for repeated attempts

- .github/workflows/luacheck.yml
The workflow is currently broken because LuaRocks' package registry seems to serve a manifest that's too large for LuaJIT to process. There are various workarounds, the most obvious one being to replace LuaJIT with PUC's Lua interpreter. But the more I read about this problem, the more I'm convinced that I don't want to rely on the LuaRocks ecosystem for this particular task.
> Replace the luacheck CI setup with a curl command
