Options_Defaults.lua

Urgolax is in Vale of Eternal Blossoms, not inside Shrine within the Vale

DB: Correct MapID for Urgloax/Chalice of Secrets

---

Options_Defaults.lua

DB: Added missing questId for the pets Devoured Wader & Bottled Up Rage

Added missing questId for two pets

---

Core/EventHandlers.lua
DB/Nodes.lua
Locales.lua
Options_Defaults.lua

Added missing 9.0 toy Kevin's Party Supplies [https://www.wowhead.com/item=184447/kevins-party-supplies](https://www.wowhead.com/item=184447/kevins-party-supplies)
Also just aligned another item properly because it was annoying to look at

DB: Added missing toy Kevin's Party Supplies

---

Core/EventHandlers.lua
DB/Nodes.lua
Locales.lua
Options_Defaults.lua

Added the 9.0 pet [Silvershell Snapper](https://www.wowhead.com/item=180856/silvershell-snapper).

DB: Added Silvershell Snapper (pet)

---

DB/Nodes.lua
Locales.lua

Added the missing fishing nodes from Shadowlands aswell as some missing from Battle for Azeroth. This should be enough to close issue #221. Not sure if the nodes for mining and such needs to be added as well(?)

Added missing fishing nodes

---

Locales.lua
Options_Defaults.lua

Added the Legion mount [Smoldering Ember Wyrm](https://www.wowhead.com/item=142552/smoldering-ember-wyrm) from Karazhan. I know the drop rate is clunky and complicated, but given that this mount is soloable, it's pretty much a flat 20% drop chance. This closes #202

DB: Added Smoldering Ember Wyrm. This closes #202

---

DB/Items/Toys/Classic.lua
Locales.lua

DB: Add tracking for Piccolo of the Flaming Fire

---

DB/Mounts/HolidayEvents.lua
DB/Pets/HolidayEvents.lua
DB/Toys/HolidayEvents.lua

Went over the list of holiday related items and added any missing holidayTextures. This closes #289.

DB: Added holidayTexture for missing Holiday related items

---

DB/Mounts/Shadowlands.lua
DB/Toys/Shadowlands.lua

Updated droprates for the 3 Necrorays as well as the egg.

DB: Updated the droprates on the Necrorays to be more accurate

---

Core/GUI/FauxAchievementPopup.lua

Update the faux achievement toast UI to be consistent with Blizzard's 9.1 version

---

DB/Pets/Shadowlands.lua
Locales.lua

Added tracking for the battle pet daily reward Squibbles. This closes #367.

DB: Added tracking for Squibbles

---

DB/Mounts/Shadowlands.lua
DB/Toys/Shadowlands.lua

Found the questIds for a handful of rares I tried to kill myself; so here they are.
See commit messages for which ones

Added defeat detection for some 9.1 items

---

DB/Pets/Shadowlands.lua

Added defeat detection and corrected coordinates

Some adjustments to Korthian Specimen

---

.github/workflows/luacheck.yml

What gets measured, gets managed... or so people say!

Add GitHub Actions workflow to perform static analysis on every commit

---

Core.lua
Core/EventHandlers.lua

While the bug is fixed, we should likely do some refactoring and write a test to make sure it can't happen again. That's still TODO since I didn't have time.

Fix attempts detection for items using the COLLECTION method

---

Utils/Sorting.lua

Added profiling labels to SortGroup() to allow profiling it

---

Core/GUI/DataBrokerDisplay.lua
Core/GUI/MainWindow.lua
Core/Interoperability/LibQTip/Tooltips.lua
Rarity.toc

While these are strewn all over the code, any attempt at streamlining the GUI will be complicated.

EncapsulatedLibQTip calls in a separate wrapper API

---

.luacheckrc
Core/EventHandlers.lua
Core/Interoperability/WoWUnit/Testing.lua
Locales.lua
Rarity.toc
Tests/Core/DatabaseValidation/TestNothing.lua
Tests/RunAllTests.lua
Tests/luaunit.lua

This PR adds the following features:
* Integration with the ``WoWUnit`` testing addon (despite the name, we use it for integration tests)
* ``/rarity test`` to run the full integration test suite... that doesn't currently exist, but one step at a time
* LuaUnit integration for offline tests (used for the actual unit tests, i.e. anything that doesn't require ingame events)
We obviously can't automate the integration tests that can only do useful things ingame, but we can run them easily and that's far better than what we have now, which is nothing.

Integrate WoWUnit and LuaUnit test frameworks to faciliate (semi-) automated testing

---

Modules/Options/Options.lua

Remove blank lines from Options.lua

---

DB/Toys/Shadowlands.lua
Locales.lua

Added the 4 new covenant calling toys that came with 9.1.5. This closes #432

Tracking for the new covenant toys from Calling Boxes

---

DB/Toys/Shadowlands.lua

Didn't think about grabbing this also earlier, but here it is

Added defeat detection for Torglluun (Bottled Shade Heart)

---

DB/Pets/Shadowlands.lua

Update drop rate for [Golden Eye](https://www.wowhead.com/item=186564/golden-eye) as it finally has some more recorded data.

Adjusted drop rate for Golden Eye

---

DB/Toys/BattleForAzeroth.lua

Added defeat detection and removed the group settings on the [Viable Cobra Egg](https://www.wowhead.com/item=160832/viable-cobra-egg)

Adjustments to Viable Cobra Egg

---

DB/Mounts/Shadowlands.lua

Adjusted droprate for Spectral Mawrat's Tail

---

.github/workflows/check-format.yaml
Modules/Options/Options.lua

Not sure if this will help with the strange autoformat errors that only occur in the CI runner, but it probably won't hurt either way...

Pin the StyLua version used by GitHub Actions runners

---

DB/Pets/Dragonflight.lua
Locales.lua

Added two of the pets as per #516. These are the ones from 'hunts'

A couple DF pets

---

DB/Mounts/Shadowlands.lua

Update the groupSize of various Shadowlands mounts

---

DB/Pets/Dragonflight.lua
Locales.lua

forbidden reach map id addition might be a duplicate

Add Gilded Mechafrog pet (Dragonflight/10.0.7)

---

Core/EventHandlers.lua
README.MD

Add a /rarity mapinfo command to find UI Map IDs more easily

---

Core.lua
Core/Collections.lua
Core/EventHandlers.lua

Fix the archaeology history bug from 10.1.5

---

Core/EventHandlers.lua
Core/GUI/AnchoredTrackingBar.lua
Core/GUI/DataBrokerDisplay.lua

As requested on Discord. May rename the command later since I'm not sure about the name, but that's easy enough to change.

Add a slash command to toggle the progress bar

---

DB/Mounts/Dragonflight.lua
Locales.lua

Added the 'collection items' mount Gooey Snailemental. This closes #567

Added Gooey Snailemental

---

Libs/LibBars-1.0/LibBars-1.0.lua

It seems that the version included with Rarity was modified, and so it shouldn't have been overwritten. The last official release on WowAce is from 2008 and no longer works.

Restore the modified LibBars-1.0 version

---

DB/SharedConstants.lua
DB/Toys/Dragonflight.lua
Locales.lua

Resolves #514 - except for the one item that has been moved to a separate issue.

Add some missing Dragonflight toys to the database

---

DB/Toys/Dragonflight.lua
Locales.lua

Untested like the rest, but it should work in as far as the container detection doesn't bug out...

Add tracking for Cloak of Many Faces

---

DB/Toys/Dragonflight.lua
Locales.lua

Add 10.1.0 toys to the database

---

DB/Toys/Dragonflight.lua
Locales.lua

It looks like this used to be purchasable, but now it's a rare drop.

Add Bag of Furious Winds (toy)

---

Locales.lua
Modules/Options/Options.lua

As requested on Discord. Definitely a niche use case, but oh well.

Add an experimental button to untrack all mounts

---

DB/Pets/Dragonflight.lua
Locales.lua

Resolves #591 - at least partially, since there appears to be a world object that also need to be tracked (separate issue).

Add 10.1.0 pets to the database

---

Core/EventHandlers.lua

These don't really help and rather drown out more important things.

Remove some of the spammy debug messages

---

Core/EventHandlers.lua
DB/Nodes.lua
DB/Toys/Dragonflight.lua
Locales.lua

only added 2/3 of the holo viewer toys because the scarlet queen one is around 60% drop rate according to wowhead.

Add Holoviewer toys to the database

---

DB/Mounts/Legion.lua
DB/Mounts/Shadowlands.lua
DB/Toys/BattleForAzeroth.lua
DB/Toys/Legion.lua

Don't see the point of these, can always restore if need be.

Remove some obsolete comments from the DB

---

Core/EventHandlers.lua

Those don't add much now, do they?

Remove more spammy debug messages

---

DB/Mounts/Dragonflight.lua
DB/Pets/Dragonflight.lua
DB/Toys/Dragonflight.lua

Add defeat detection for various 10.x collectibles

---

Core/EventHandlers.lua

Split off from #622 - thanks to @Rubio9 for catching and fixing this :)

Move some existing comments to their proper places

---

Core/EventHandlers.lua

Fix duplicate attempts for boss drops with kill statistics

---

DB/Pets/MistsOfPandaria.lua

Just grabbed this while testing something unrelated.

Add defeat detection for Dandelion Frolicker (pet)

---

Core/EventHandlers.lua

This should preferably be covered by unit tests (if possible).

Remove another batch of spammy debug messages

---

DB/SharedConstants.lua
DB/Toys/Dragonflight.lua
Locales.lua

Add Molten Laval Ball (10.2.0 toy) to the database

---

.luacheckrc
Core/EventHandlers.lua
DB/Pets/Dragonflight.lua
DB/SharedConstants.lua
Locales.lua

some things to do - possibly, if it even works.

Implement tracking for Brul (pet)

---

DB/Toys/HolidayEvents.lua
Locales.lua

Add Festive Trans-Dimensional Bird Whistle to the DB

---

Core.lua
Core/EventHandlers.lua

Fix multiple attempts being added from Pick Pocket

---

DB/Mounts/BattleForAzeroth.lua

I've been told (on Discord) that this is now solo-able.

Update the category for Mechagon Peacekeeper

---

Core/EventHandlers.lua
DB/Pets/TheWarWithin.lua
DB/Spells.lua
Locales.lua

Add tracking for Thaumaturgy (Writhing Transmutagen pet)

---

Options_Defaults.lua

Add tracking for TWW achievement rares

---

Locales.lua
Modules/Options/Options.lua

Added a toggle for the progress bar

---

DB/Mounts/TheWarWithin.lua
Locales.lua

Data provided by Ellezanor (on Discord).

Add Undermine paragon mounts to the database

---

DB/Mounts/TheWarWithin.lua
DB/Pets/TheWarWithin.lua
DB/Toys/TheWarWithin.lua

There wasn't any data for these items on wowhead previously, but there is now.

Update placeholder drop rates for TWW collectibles

---

DB/Mounts/TheWarWithin.lua
Locales.lua

Data provided by Ellezanor on Discord.

Add Steamwheedle Supplier (mount)

---

DB/Mounts/TheWarWithin.lua
Locales.lua

Data provided by Ellezanor on Discord.

Add tracking for Void-Scarred Lynx (11.1.5 mount)

---

DB/Pets/Legion.lua
DB/Pets/MistsOfPandaria.lua
DB/Toys/Shadowlands.lua

Extracted from #891 since this is unrelated to the LibBars PR.

Fix several validation errors

---

DB/Pets/Shadowlands.lua

Reported by $Rince on Discord.

Update the difficulty and chance for Gizmo (Tazavesh pet)

---

CHANGES.MD
Changes.lua

Addresses https://www.wowace.com/projects/rarity?comment=3108

Update the changelog for r746-release-2
